site_name: Documentation Center
site_author: Marquis Kurt
site_description: The official documentation center for Unscripted projects
copyright: "Copyright &copy; 2020 Marquis Kurt."

theme:
  name: material
  logo: "resources/logo-bubble.svg"
  font:
    text: "Inter"
    code: "JetBrains Mono"
  palette:
    accent: "light blue"
    scheme: "preference"
  features:
    - tabs
    - instant

extra_css:
  - "https://rsms.me/inter/inter.css"
  - "stylesheets/uvn.css"
  - "stylesheets/ayu.css"

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/highlight.min.js
  - "scripts/highlight.js"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: false
  - toc:
      permalink: true
